server:
  forward-headers-strategy: native

spring:
  application:
    name: dodo-server

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_LOCAL_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "http://32.236.80.153.nip.io:8080/login/oauth2/code/google"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_EXPIRATION_ACCESS}
    refresh: ${JWT_EXPIRATION_REFRESH}

app:
  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000/admin/login/callback
      - https://sw-capstone-frontend-*-jeonguihoons-projects.vercel.app/admin/login/callback
      - https://sw-capstone-frontend.vercel.app/admin/login/callback

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.results: INFO
    com.dodo.dodoserver: DEBUG


firebase:
  service-account:
    path: "/firebase/service-account.json"

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
    cloudfront-domain: ${AWS_CLOUDFRONT_DOMAIN}